# Generated by Django 6.0.5 on 2026-05-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('balloon', 'Balloon'), ('chocolate', 'Chocolate'), ('teddy', 'Teddy Bear')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('includes_list', models.TextField(help_text='Enter items separated by commas')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_best_seller', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=True)),
                ('price_regular_srp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_regular_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_deluxe_srp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_deluxe_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_premium_srp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_premium_current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
            ],
        ),
    ]
